-
    title: "Why Privacy Matters Even if You Have 'Nothing to Hide'"
    authors:
        - Daniel J. Solove
    url: https://chronicle.com/article/Why-Privacy-Matters-Even-if/127461/
    language: "Anglais"

-
    title: "'I've Got Nothing to Hide' and Other Misunderstandings of Privacy"
    authors:
        - Daniel J. Solove
    url: http://papers.ssrn.com/sol3/papers.cfm?abstract_id=998565
    language: "Anglais"

-
    title: "Pad Framasoft"
    authors:
        - Document partagé
    url: https://lite2.framapad.org/p/rien-a-cacher
    language: "Français"
