-
    url: https://www.laquadrature.net/
    image: logo_laquadrature-net_horiz_moyen.png

-
    url: https://www.lemonde.fr/blog/bugbrother/
    image: bug-brother.jpg

-
    url: https://reflets.info/
    image: logo-reflets.png
