-
    url: https://www.laquadrature.net/fr/
    image: logo_laquadrature-net_horiz_moyen.png

-
    url: http://bugbrother.blog.lemonde.fr/
    image: bug-brother.jpg

-
    url: http://reflets.info/
    image: logo-reflets.png
