-
    title: "Why Privacy Matters Even if You Have 'Nothing to Hide'"
    authors:
        - Daniel J. Solove
    url: https://chronicle.com/article/Why-Privacy-Matters-Even-if/127461/
    language: "Anglais"
